export const driverDummyData = [
  {
    rank: 1,
    driver: 'Max Verstappen',
    number: 1,
    nationality: 'NED',
    team: 'Red Bull',
    points: 281,
  },
  {
    rank: 2,
    driver: 'Charles Leclerc',
    number: 16,
    nationality: 'MON',
    team: 'Ferrari',
    points: 210,
  },
  {
    rank: 3,
    driver: 'Lewis Hamilton',
    number: 44,
    nationality: 'GBR',
    team: 'Mercedes',
    points: 195,
  },
  {
    rank: 4,
    driver: 'Lando Norris',
    number: 4,
    nationality: 'GBR',
    team: 'McLaren',
    points: 182,
  },
  {
    rank: 5,
    driver: 'Carlos Sainz',
    number: 55,
    nationality: 'ESP',
    team: 'Ferrari',
    points: 165,
  },
  {
    rank: 6,
    driver: 'George Russell',
    number: 63,
    nationality: 'GBR',
    team: 'Mercedes',
    points: 142,
  },
  {
    rank: 7,
    driver: 'Sergio Pérez',
    number: 11,
    nationality: 'MEX',
    team: 'Red Bull',
    points: 130,
  },
  {
    rank: 8,
    driver: 'Oscar Piastri',
    number: 81,
    nationality: 'AUS',
    team: 'McLaren',
    points: 118,
  },
  {
    rank: 9,
    driver: 'Fernando Alonso',
    number: 14,
    nationality: 'ESP',
    team: 'Aston Martin',
    points: 110,
  },
  {
    rank: 10,
    driver: 'Pierre Gasly',
    number: 10,
    nationality: 'FRA',
    team: 'Alpine',
    points: 92,
  },
  {
    rank: 11,
    driver: 'Esteban Ocon',
    number: 31,
    nationality: 'FRA',
    team: 'Alpine',
    points: 75,
  },
  {
    rank: 12,
    driver: 'Yuki Tsunoda',
    number: 22,
    nationality: 'JPN',
    team: 'RB (Visa Cash App RB)',
    points: 62,
  },
  {
    rank: 13,
    driver: 'Valtteri Bottas',
    number: 77,
    nationality: 'FIN',
    team: 'Kick Sauber',
    points: 55,
  },
  {
    rank: 14,
    driver: 'Kevin Magnussen',
    number: 20,
    nationality: 'DEN',
    team: 'Haas',
    points: 48,
  },
  {
    rank: 15,
    driver: 'Alexander Albon',
    number: 23,
    nationality: 'THA',
    team: 'Williams',
    points: 42,
  },
  {
    rank: 16,
    driver: 'Nico Hülkenberg',
    number: 27,
    nationality: 'GER',
    team: 'Haas',
    points: 36,
  },
  {
    rank: 17,
    driver: 'Guanyu Zhou',
    number: 24,
    nationality: 'CHN',
    team: 'Kick Sauber',
    points: 28,
  },
  {
    rank: 18,
    driver: 'Logan Sargeant',
    number: 2,
    nationality: 'USA',
    team: 'Williams',
    points: 15,
  },
  {
    rank: 19,
    driver: 'Daniel Ricciardo',
    number: 3,
    nationality: 'AUS',
    team: 'RB (Visa Cash App RB)',
    points: 10,
  },
  {
    rank: 20,
    driver: 'Lance Stroll',
    number: 18,
    nationality: 'CAN',
    team: 'Aston Martin',
    points: 8,
  },
];

export const teamDummyData = [
  { rank: 1, team: 'Red Bull Racing', points: 411 },
  { rank: 2, team: 'Ferrari', points: 375 },
  { rank: 3, team: 'Mercedes', points: 350 },
  { rank: 4, team: 'McLaren', points: 325 },
  { rank: 5, team: 'Aston Martin', points: 210 },
  { rank: 6, team: 'Alpine', points: 175 },
  { rank: 7, team: 'Williams', points: 120 },
  { rank: 8, team: 'RB (Visa Cash App RB)', points: 95 },
  { rank: 9, team: 'Haas', points: 65 },
  { rank: 10, team: 'Kick Sauber', points: 40 },
];
