import type { Metadata } from 'next';
import './globals.css';
import Header from './components/common/ui/Header';
import Footer from './components/common/ui/Footer';
import Provider from './Provider';

export const metadata: Metadata = {
  title: 'F1 project',
  description: 'Generated by create next app',
  icons: {
    icon: '/f1.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0B0B0B] text-[#ffffff]">
        <Provider>
          <Header />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
