import type { Metadata, Viewport } from 'next';
import './globals.css';
import './root.css';
import Header from './components/common/ui/Header';
import Footer from './components/common/ui/Footer';
import Provider from './Provider';
import MobileFooter from './components/mobile/MobileFooter';

export const metadata: Metadata = {
  title: 'AfterLap',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    icon: '/AfterLapLogo.svg',
    apple: '/icons/icon-192.png',
  },
};

export const viewport: Viewport = {
  themeColor: '#0B0B0B',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        {/* iPhone 14 / 15 Pro Max */}
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1290-2796.jpg"
          media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />

        {/* iPhone 14 / 15 Pro  */}
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1179-2556.jpg"
          media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />

        {/* iPhone 12 / 13 / 14  */}
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1170-2532.jpg"
          media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
        />
        {/* iPad Pro 12.9  */}
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-2048-2732.jpg"
          media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />

        {/* iPad Pro 11  */}
        <link
          rel="apple-touch-startup-image"
          href="/splash/apple-splash-1668-2388.jpg"
          media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
        />
      </head>
      <body className="bg-[#0B0B0B] text-[#ffffff]">
        <Provider>
          <Header />
          <div className="min-h-screen pb-12 lg:pb-0">{children}</div>
          <Footer />
          <MobileFooter />
        </Provider>
      </body>
    </html>
  );
}
