import type { Metadata } from 'next';
import './globals.css';
import Header from './components/common/ui/Header';

export const metadata: Metadata = {
  title: 'F1 project',
  description: 'Generated by create next app',
  icons: {
    icon: '/f1.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-[1440px] mx-auto bg-[#0B0B0B] text-[#ffffff]">
        <Header />

        {children}
      </body>
    </html>
  );
}
